window.CATALOG = {
  products: [
    {
      id: 'fusion-v3',
      name: 'Fusion V3',
      manufacturer: 'Dover Fueling Solutions',
      category: 'Forecourt Controller',
      tagline: 'Controlador de patio Fusion de tercera generación',
      description:
        'Controlador industrial Fusion V3 de Dover Fueling Solutions con conectividad avanzada, múltiples puertos seriales, doble LAN, GPIO y bloques terminales GRIB. Modelo 3D interactivo para exploración y señalización de componentes.',
      accent: '#0076CE',
      model3d: 'assets/models/fusion-v3.glb',
      previewImage: 'assets/images/fusion-v3/front.png',
      highlights: [
        '6 puertos seriales COM',
        'Dual LAN + USB',
        'VGA y DisplayPort',
        'GPIO + GRIB terminals',
      ],
      documentation: [
        { id: 'front', title: 'Vista frontal', caption: 'Chasis Fusion V3 con panel frontal brillante, display LCD de estado e indicadores LED.', src: 'assets/images/fusion-v3/front.png' },
        { id: 'back', title: 'Vista trasera', caption: 'Conectores LAN, seriales, VGA, GPIO, GRIB y terminales de audio.', src: 'assets/images/wayne-fusion/back.jpg' },
        { id: 'install', title: 'Instalación en rack', caption: 'Montaje típico del Fusion en gabinete de estación de servicio.', src: 'assets/images/wayne-fusion/install.jpg' },
        { id: 'wiring', title: 'Cableado GRIB', caption: 'Detalle de conexión a bloques terminales y surtidores.', src: 'assets/images/wayne-fusion/wiring.jpg' },
      ],
      manuals: [
        {
          id: 'automation-server-v3-en',
          title: 'Fusion Automation Server V3',
          caption: 'Manual oficial DFS — Automation Server Version 3 (English).',
          src: 'assets/docs/fusion-v3/fusion-v3-automation-server-v3-en.pdf',
          language: 'EN',
        },
      ],
      markers: {
        features: [
          { id: 'usb', label: 'USB', type: 'USB-A', x: 41, y: 50, orbit: '0deg 75deg 110%', desc: 'Puerto USB-A para mantenimiento, copias de respaldo y configuración local del equipo.' },
          { id: 'com5', label: 'COM5', type: 'DB9 Serial', x: 48, y: 42, orbit: '340deg 72deg 112%', desc: 'Puerto serial DB9 COM5. Comunicación con periféricos del patio.' },
          { id: 'com6', label: 'COM6', type: 'DB9 Serial', x: 48, y: 58, orbit: '20deg 72deg 112%', desc: 'Puerto serial DB9 COM6. Segundo canal serial frontal.' },
          { id: 'status', label: 'STATUS', type: 'LCD Display', x: 58, y: 50, orbit: '0deg 78deg 108%', desc: 'Pantalla LCD de estado del sistema. Muestra información operativa del Fusion.' },
          { id: 'power', label: 'POWER', type: 'LED Indicator', x: 67, y: 42, orbit: '25deg 70deg 113%', desc: 'LED indicador de alimentación eléctrica. Verde = equipo encendido.' },
          { id: 'gribs', label: 'GRIBS', type: 'LED Indicator', x: 67, y: 58, orbit: '335deg 70deg 113%', desc: 'LED de estado GRIBS. Indica actividad en bus de surtidores.' },
          { id: 'pwr', label: 'PWR', type: 'Power Switch', x: 77, y: 50, orbit: '45deg 75deg 115%', desc: 'Interruptor principal de encendido/apagado del controlador.' },
          { id: 'lan1', label: 'LAN1/USB', type: 'RJ45 + 2× USB', x: 42, y: 28, orbit: '180deg 70deg 115%', desc: 'Ethernet LAN1 con dos puertos USB-A integrados.' },
          { id: 'lan2', label: 'LAN2/USB', type: 'RJ45 + 2× USB', x: 52, y: 28, orbit: '200deg 70deg 115%', desc: 'Ethernet LAN2 redundante con dos puertos USB-A.' },
          { id: 'grib', label: 'GRIB 3/5/6', type: 'Terminal Blocks', x: 82, y: 44, orbit: '90deg 75deg 112%', desc: 'Bloques terminales GRIB para cableado de surtidores y periféricos.' },
        ],
      },
    },
    {
      id: 'fusion-v2',
      name: 'Fusion V2',
      manufacturer: 'Dover Fueling Solutions',
      category: 'Forecourt Controller',
      tagline: 'Controlador de patio Fusion segunda generación',
      description:
        'Controlador Fusion V2 con conectividad serial, Ethernet dual, GPIO y terminales GRIB para integración en estaciones de servicio. Modelo 3D interactivo para exploración y señalización de componentes.',
      accent: '#005A9C',
      model3d: 'assets/models/fusion-v2.glb',
      previewImage: 'assets/images/fusion-v2/model-preview.png',
      highlights: [
        '6 puertos seriales COM',
        'Dual LAN + USB',
        'VGA y DisplayPort',
        'Modelo 3D interactivo',
      ],
      documentation: [
        { id: 'model-preview', title: 'Vista del modelo 3D', caption: 'Vista previa del modelo SketchUp Fusion V2 (archivo actualizado).', src: 'assets/images/fusion-v2/model-preview.png' },
        { id: 'front', title: 'Vista frontal', caption: 'Panel frontal con puertos COM, USB, display de estado e interruptor PWR.', src: 'assets/images/wayne-fusion/front.jpg' },
        { id: 'back', title: 'Vista trasera', caption: 'Conectores LAN, seriales, VGA, GPIO, GRIB y terminales de audio.', src: 'assets/images/wayne-fusion/back.jpg' },
      ],
      manuals: [
        {
          id: 'model-skp',
          title: 'Modelo 3D SketchUp',
          caption: 'Archivo fuente SketchUp Fusion V2 (.skp). Para actualizar el visor 3D del catálogo, exporte desde SketchUp como GLB y reemplace assets/models/fusion-v2.glb.',
          src: 'assets/models/fusion-v2.skp',
          language: 'SKP',
        },
      ],
      markers: {
        features: [
          { id: 'usb', label: 'USB', type: 'USB-A', x: 41, y: 50, orbit: '0deg 75deg 110%', desc: 'Puerto USB-A para mantenimiento, copias de respaldo y configuración local del equipo.' },
          { id: 'com5', label: 'COM5', type: 'DB9 Serial', x: 48, y: 42, orbit: '340deg 72deg 112%', desc: 'Puerto serial DB9 COM5. Comunicación con periféricos del patio.' },
          { id: 'com6', label: 'COM6', type: 'DB9 Serial', x: 48, y: 58, orbit: '20deg 72deg 112%', desc: 'Puerto serial DB9 COM6. Segundo canal serial frontal.' },
          { id: 'status', label: 'STATUS', type: 'LCD Display', x: 58, y: 50, orbit: '0deg 78deg 108%', desc: 'Pantalla LCD de estado del sistema. Muestra información operativa del Fusion.' },
          { id: 'power', label: 'POWER', type: 'LED Indicator', x: 67, y: 42, orbit: '25deg 70deg 113%', desc: 'LED indicador de alimentación eléctrica. Verde = equipo encendido.' },
          { id: 'gribs', label: 'GRIBS', type: 'LED Indicator', x: 67, y: 58, orbit: '335deg 70deg 113%', desc: 'LED de estado GRIBS. Indica actividad en bus de surtidores.' },
          { id: 'pwr', label: 'PWR', type: 'Power Switch', x: 77, y: 50, orbit: '45deg 75deg 115%', desc: 'Interruptor principal de encendido/apagado del controlador.' },
          { id: 'lan1', label: 'LAN1/USB', type: 'RJ45 + 2× USB', x: 42, y: 28, orbit: '180deg 70deg 115%', desc: 'Ethernet LAN1 con dos puertos USB-A integrados.' },
          { id: 'lan2', label: 'LAN2/USB', type: 'RJ45 + 2× USB', x: 52, y: 28, orbit: '200deg 70deg 115%', desc: 'Ethernet LAN2 redundante con dos puertos USB-A.' },
          { id: 'grib', label: 'GRIB 3/5/6', type: 'Terminal Blocks', x: 82, y: 44, orbit: '90deg 75deg 112%', desc: 'Bloques terminales GRIB para cableado de surtidores y periféricos.' },
          { id: 'vga', label: 'VGA', type: 'Video Output', x: 32, y: 36, orbit: '270deg 72deg 112%', desc: 'Salida de video VGA para monitor local o consola.' },
          { id: 'gpio', label: 'GPIO', type: '4-pin Terminal', x: 60, y: 16, orbit: '250deg 68deg 114%', desc: 'Bloque GPIO de 4 pines para entradas/salidas digitales.' },
        ],
      },
    },
    {
      id: 'pos-a80',
      name: 'POS A80',
      manufacturer: 'Terminal de Pago',
      category: 'Payment Terminal',
      tagline: 'Terminal POS compacto con pagos chip, banda y contactless',
      description:
        'Terminal de pago POS A80 con pantalla táctil, teclado físico, lector de chip EMV, banda magnética, NFC contactless e impresora térmica integrada. Modelo 3D interactivo para exploración y señalización de componentes.',
      accent: '#00BFA5',
      model3d: 'assets/models/pos-a80.glb',
      highlights: [
        'Pantalla táctil',
        'Chip + banda magnética',
        'Contactless NFC',
        'Impresora térmica',
      ],
      documentation: [
        { id: 'overview', title: 'Vista general', caption: 'Terminal POS A80 en mostrador de caja.', src: 'assets/images/pos-a80/overview.jpg' },
        { id: 'front', title: 'Vista frontal', caption: 'Pantalla, teclado y zonas de lectura de tarjetas.', src: 'assets/images/pos-a80/front.jpg' },
        { id: 'side', title: 'Vista lateral', caption: 'Perfil del terminal y ranuras de impresión.', src: 'assets/images/pos-a80/side.jpg' },
        { id: 'connections', title: 'Conexiones', caption: 'Puertos de alimentación, red y periféricos.', src: 'assets/images/pos-a80/connections.jpg' },
      ],
      markers: {
        features: [
          { id: 'screen', label: 'Pantalla', type: 'Táctil LCD', x: 50, y: 34, orbit: '0deg 75deg 110%', desc: 'Pantalla táctil a color para operación, menús y firma digital del cliente.' },
          { id: 'contactless', label: 'Contactless', type: 'NFC / Tap', x: 50, y: 22, orbit: '0deg 62deg 105%', desc: 'Antena NFC para pagos sin contacto con tarjetas y wallets móviles.' },
          { id: 'keypad', label: 'Teclado', type: 'PIN Pad', x: 50, y: 62, orbit: '0deg 82deg 108%', desc: 'Teclado físico para ingreso de PIN y navegación del terminal.' },
          { id: 'chip', label: 'Lector Chip', type: 'EMV', x: 36, y: 46, orbit: '340deg 75deg 112%', desc: 'Ranura lectora de chip EMV para tarjetas con contacto.' },
          { id: 'magnetic', label: 'Banda Magnética', type: 'Swipe', x: 64, y: 48, orbit: '20deg 75deg 112%', desc: 'Lector de banda magnética para tarjetas deslizadas.' },
          { id: 'printer', label: 'Impresora', type: 'Térmica', x: 50, y: 10, orbit: '180deg 70deg 115%', desc: 'Impresora térmica integrada para vouchers y comprobantes de pago.' },
        ],
      },
    },
    {
      id: 'gilbarco-encore-500s',
      name: 'Encore 500S',
      manufacturer: 'Gilbarco Veeder-Root',
      category: 'Fuel Dispenser',
      tagline: 'Surtidor de combustible de alto rendimiento con pagos integrados',
      description:
        'Surtidor Gilbarco Encore 500S con pantalla multimedia, terminal de pago integrado, lectura contactless, múltiples mangueras y comunicación con el controlador de patio. Modelo 3D interactivo para exploración y señalización de componentes.',
      accent: '#E31837',
      model3d: 'assets/models/gilbarco-encore-500s.glb',
      highlights: [
        'Pantalla multimedia',
        'Pagos chip y contactless',
        'Multi-manguera',
        'Comunicación Fusion',
      ],
      documentation: [
        { id: 'overview', title: 'Vista general', caption: 'Surtidor Encore 500S en isla de combustible.', src: 'assets/images/gilbarco-encore-500s/overview.jpg' },
        { id: 'front', title: 'Vista frontal', caption: 'Pantalla multimedia, terminal de pago y selección de producto.', src: 'assets/images/gilbarco-encore-500s/front.jpg' },
        { id: 'nozzles', title: 'Mangueras', caption: 'Pistolas y mangueras de dispensado.', src: 'assets/images/gilbarco-encore-500s/nozzles.jpg' },
        { id: 'install', title: 'Instalación', caption: 'Montaje en isla y conexión al controlador de patio.', src: 'assets/images/gilbarco-encore-500s/install.jpg' },
      ],
      markers: {
        features: [
          { id: 'display', label: 'Pantalla', type: 'Multimedia LCD', x: 50, y: 28, orbit: '0deg 75deg 110%', desc: 'Pantalla a color para selección de combustible, publicidad y mensajes al cliente.' },
          { id: 'payment', label: 'Terminal de Pago', type: 'EMV / NFC', x: 50, y: 42, orbit: '0deg 78deg 108%', desc: 'Terminal integrado para pagos con chip, banda magnética y contactless.' },
          { id: 'contactless', label: 'Contactless', type: 'NFC / Tap', x: 42, y: 38, orbit: '340deg 72deg 112%', desc: 'Antena NFC para pagos sin contacto con tarjetas y wallets móviles.' },
          { id: 'nozzle-a', label: 'Manguera A', type: 'Dispensing Hose', x: 28, y: 55, orbit: '300deg 80deg 115%', desc: 'Manguera y pistola de dispensado para primer producto (ej. gasolina regular).' },
          { id: 'nozzle-b', label: 'Manguera B', type: 'Dispensing Hose', x: 72, y: 55, orbit: '60deg 80deg 115%', desc: 'Segunda manguera para producto adicional (ej. premium o diésel).' },
          { id: 'grade-select', label: 'Selección', type: 'Grade Buttons', x: 50, y: 52, orbit: '0deg 82deg 106%', desc: 'Controles de selección de tipo de combustible y confirmación de carga.' },
          { id: 'printer', label: 'Impresora', type: 'Térmica', x: 58, y: 34, orbit: '25deg 70deg 113%', desc: 'Impresora térmica para comprobantes y vouchers de transacción.' },
        ],
      },
    },
    {
      id: 'cisco-catalyst-2960s-48td-l',
      name: 'Catalyst 2960S-48TD-L',
      manufacturer: 'Cisco',
      category: 'Network Switch',
      tagline: 'Switch de acceso Layer 2 de 48 puertos Gigabit con uplinks SFP',
      description:
        'Switch Cisco Catalyst 2960S-48TD-L con 48 puertos Ethernet 10/100/1000, 2 uplinks combo SFP, consola RJ-45 y USB, LEDs de estado y apilamiento FlexStack. Modelo 3D interactivo para exploración y señalización de interfaces.',
      accent: '#049FD9',
      model3d: 'assets/models/cisco-catalyst-2960s-48td-l.glb',
      previewImage: 'assets/images/cisco-catalyst-2960s-48td-l/front.png',
      highlights: [
        '48 puertos Gigabit Ethernet',
        '2 uplinks combo SFP',
        'Consola RJ-45 + USB',
        'Apilamiento FlexStack',
      ],
      documentation: [
        { id: 'front', title: 'Vista frontal', caption: 'Catalyst 2960 — 48 puertos RJ-45, LEDs de estado, consola, USB y uplinks SFP.', src: 'assets/images/cisco-catalyst-2960s-48td-l/front.png' },
        { id: 'rear', title: 'Vista trasera', caption: 'Conector de alimentación AC, ventilación y puertos de stack FlexStack.', src: 'assets/images/placeholder-back.svg' },
      ],
      manuals: [
        {
          id: 'datasheet-2960s',
          title: 'Datasheet Catalyst 2960-S',
          caption: 'Ficha técnica oficial Cisco (enlace externo).',
          src: 'https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-2960-x-series-switches/datasheet_c78-728971.html',
          external: true,
          language: 'EN',
        },
      ],
      markers: {
        features: [
          { id: 'eth-1-24', label: 'Puertos 1–24', type: 'RJ45 Gigabit', x: 38, y: 62, orbit: '0deg 75deg 110%', desc: 'Bloque frontal de 24 puertos Ethernet 10/100/1000 autonegociables con LEDs de enlace/actividad por puerto.' },
          { id: 'eth-25-48', label: 'Puertos 25–48', type: 'RJ45 Gigabit', x: 62, y: 62, orbit: '0deg 75deg 110%', desc: 'Segundo bloque de 24 puertos Gigabit para dispositivos de acceso, cámaras, POS y equipos de patio.' },
          { id: 'sfp-uplinks', label: 'Uplinks SFP', type: '2× Combo SFP', x: 78, y: 58, orbit: '0deg 72deg 112%', desc: 'Dos uplinks combo para módulos SFP/SFP+ de enlace troncal hacia core o switch superior.' },
          { id: 'console', label: 'Console', type: 'RJ45 Serial', x: 12, y: 38, orbit: '0deg 78deg 108%', desc: 'Puerto de consola RJ-45 para configuración inicial, recuperación y diagnóstico local del switch.' },
          { id: 'usb-console', label: 'USB Console', type: 'Mini-USB', x: 12, y: 52, orbit: '0deg 78deg 108%', desc: 'Puerto USB mini-B alternativo de consola para laptops sin puerto serial.' },
          { id: 'status-leds', label: 'LEDs', type: 'System Status', x: 18, y: 22, orbit: '0deg 70deg 105%', desc: 'LEDs de estado del sistema: SYS, RPS, Master, Stack, PoE (si aplica) y actividad general.' },
          { id: 'mode', label: 'MODE', type: 'Push Button', x: 28, y: 28, orbit: '0deg 72deg 106%', desc: 'Botón MODE para seleccionar modo de LEDs del panel frontal (Puerto / SPD / PoE / Stack).' },
          { id: 'pwr-in', label: 'Alimentación', type: 'AC Power', x: 50, y: 18, orbit: '180deg 70deg 115%', desc: 'Conector de alimentación AC en panel trasero. Verifique redundancia con fuente RPS si está instalada.' },
          { id: 'stack-ports', label: 'FlexStack', type: 'Stacking Module', x: 88, y: 42, orbit: '90deg 75deg 112%', desc: 'Módulo o ranuras FlexStack para apilar varios Catalyst 2960S como un solo switch lógico.' },
        ],
      },
    },
    {
      id: 'cisco-meraki-mx',
      name: 'Meraki MX',
      manufacturer: 'Cisco Meraki',
      category: 'Security Appliance',
      tagline: 'Appliance de seguridad SD-WAN con firewall y gestión en la nube',
      description:
        'Firewall Meraki MX con inspección L3/L7, VPN site-to-site, filtrado de contenido y telemetría desde Meraki Dashboard. Modelo 3D interactivo para exploración y señalización de puertos WAN, LAN y periféricos.',
      accent: '#78BE20',
      model3d: 'assets/models/cisco-meraki-mx.glb',
      highlights: [
        'Firewall y SD-WAN',
        'Gestión Meraki Dashboard',
        'VPN site-to-site',
        'Puertos WAN/LAN + USB',
      ],
      documentation: [
        { id: 'front', title: 'Vista frontal', caption: 'Puertos WAN/LAN, LED de estado y botón reset del appliance Meraki MX.', src: 'assets/images/placeholder-front.svg' },
        { id: 'rear', title: 'Vista trasera', caption: 'Alimentación DC y conectores traseros según modelo.', src: 'assets/images/placeholder-back.svg' },
      ],
      manuals: [
        {
          id: 'meraki-mx-docs',
          title: 'Documentación Meraki MX',
          caption: 'Portal oficial de documentación Cisco Meraki (enlace externo).',
          src: 'https://documentation.meraki.com/MX/MX_Overview_and_Specifications/MX_Datasheets',
          external: true,
          language: 'EN',
        },
      ],
      markers: {
        features: [
          { id: 'wan', label: 'WAN', type: 'RJ45 / SFP', x: 22, y: 58, orbit: '0deg 75deg 110%', desc: 'Puerto WAN principal hacia internet o enlace MPLS. Configuración de IP, DHCP o PPPoE desde Dashboard.' },
          { id: 'lan-ports', label: 'LAN 1–4', type: 'RJ45 Gigabit', x: 50, y: 62, orbit: '0deg 75deg 110%', desc: 'Puertos LAN internos para red de estación, switches de acceso, POS y cámaras.' },
          { id: 'usb', label: 'USB', type: 'USB-A', x: 78, y: 52, orbit: '0deg 72deg 112%', desc: 'Puerto USB para modem celular 4G/LTE de respaldo o almacenamiento según modelo y licencia.' },
          { id: 'status-led', label: 'Status', type: 'LED Indicator', x: 18, y: 28, orbit: '0deg 70deg 105%', desc: 'LED de estado del appliance. Indica arranque, conectividad a Meraki Cloud y alertas locales.' },
          { id: 'pwr-in', label: 'Alimentación', type: 'DC Power', x: 50, y: 16, orbit: '180deg 70deg 115%', desc: 'Conector de alimentación en panel trasero. Use el transformador original Meraki/Cisco.' },
          { id: 'reset', label: 'Reset', type: 'Pinhole Button', x: 72, y: 24, orbit: '0deg 68deg 108%', desc: 'Botón de reset de fábrica. Mantener presionado según manual para recuperación del equipo.' },
        ],
      },
    },
    {
      id: 'pax-im30',
      name: 'IM30',
      manufacturer: 'PAX',
      category: 'Payment Terminal',
      tagline: 'Terminal de pago Android con pantalla táctil y vista 360°',
      description:
        'Terminal de pago PAX IM30 con sistema Android, pantalla táctil, NFC contactless e impresora térmica. Incluye visualización 360° interactiva (450 fotos) para explorar el equipo desde múltiples ángulos y señalizar componentes.',
      accent: '#005BAC',
      previewImage: 'assets/spin360/im30-24/8_15.jpg',
      spin360: {
        folder: 'assets/spin360/im30-24',
        uCount: 30,
        vCount: 15,
        uWrap: true,
        vWrap: false,
        uStart: 15,
        vStart: 8,
        sensitivity: 0.2,
      },
      highlights: ['Pantalla táctil', 'Android', 'NFC contactless', 'Vista 360°'],
      documentation: [],
      markers: {
        features: [
          { id: 'screen', label: 'Pantalla', type: 'Táctil LCD', x: 50, y: 34, uIndex: 15, vIndex: 8, desc: 'Pantalla táctil a color para operación, menús y firma digital del cliente.' },
          { id: 'contactless', label: 'Contactless', type: 'NFC / Tap', x: 50, y: 22, uIndex: 15, vIndex: 8, desc: 'Antena NFC para pagos sin contacto con tarjetas y wallets móviles.' },
          { id: 'keypad', label: 'Teclado', type: 'PIN Pad', x: 50, y: 62, uIndex: 15, vIndex: 8, desc: 'Teclado físico para ingreso de PIN y navegación del terminal.' },
          { id: 'chip', label: 'Lector Chip', type: 'EMV', x: 36, y: 46, uIndex: 12, vIndex: 8, desc: 'Ranura lectora de chip EMV para tarjetas con contacto.' },
          { id: 'magnetic', label: 'Banda Magnética', type: 'Swipe', x: 64, y: 48, uIndex: 18, vIndex: 8, desc: 'Lector de banda magnética para tarjetas deslizadas.' },
          { id: 'printer', label: 'Impresora', type: 'Térmica', x: 50, y: 10, uIndex: 15, vIndex: 6, desc: 'Impresora térmica integrada para vouchers y comprobantes de pago.' },
        ],
      },
    },
    {
      id: 'pax-a920-pro',
      name: 'A920 Pro',
      manufacturer: 'PAX',
      category: 'Payment Terminal',
      tagline: 'Terminal Android premium con vista 360° interactiva',
      description:
        'Terminal de pago PAX A920 Pro con Android, pantalla táctil de alta resolución, NFC contactless, cámara frontal y conectividad Wi‑Fi/4G. Visualización 360° con 450 fotos para explorar el equipo y señalizar sus componentes.',
      accent: '#1A237E',
      previewImage: 'assets/spin360/a920-pro/8_15.jpg',
      spin360: {
        folder: 'assets/spin360/a920-pro',
        uCount: 30,
        vCount: 15,
        uWrap: true,
        vWrap: false,
        uStart: 15,
        vStart: 8,
        sensitivity: 0.2,
      },
      highlights: ['Android', 'Pantalla táctil HD', 'NFC contactless', 'Vista 360°'],
      documentation: [],
      markers: {
        features: [
          { id: 'screen', label: 'Pantalla', type: 'Táctil HD', x: 50, y: 32, uIndex: 15, vIndex: 8, desc: 'Pantalla táctil a color de alta resolución para operación, apps y firma digital.' },
          { id: 'contactless', label: 'Contactless', type: 'NFC / Tap', x: 50, y: 20, uIndex: 15, vIndex: 8, desc: 'Antena NFC para pagos sin contacto con tarjetas y wallets móviles.' },
          { id: 'camera', label: 'Cámara', type: 'Frontal', x: 50, y: 12, uIndex: 15, vIndex: 7, desc: 'Cámara frontal para escaneo de códigos QR y aplicaciones de identificación.' },
          { id: 'chip', label: 'Lector Chip', type: 'EMV', x: 38, y: 44, uIndex: 12, vIndex: 8, desc: 'Ranura lectora de chip EMV para tarjetas con contacto.' },
          { id: 'magnetic', label: 'Banda Magnética', type: 'Swipe', x: 62, y: 46, uIndex: 18, vIndex: 8, desc: 'Lector de banda magnética para tarjetas deslizadas.' },
          { id: 'printer', label: 'Impresora', type: 'Térmica', x: 50, y: 68, uIndex: 15, vIndex: 9, desc: 'Impresora térmica integrada para comprobantes y vouchers de pago.' },
        ],
      },
    },
    {
      id: 'cargador-voltex',
      name: 'Cargador Voltex',
      manufacturer: 'Copec Voltex',
      category: 'EV Charger',
      tagline: 'Cargador de vehículos eléctricos Copec Voltex',
      description:
        'Cargador para vehículos eléctricos Copec Voltex con conector de carga, pantalla de interacción y gabinete para instalación en estaciones de servicio y puntos de carga. Modelo 3D interactivo para exploración y señalización de componentes.',
      accent: '#00A859',
      model3d: 'assets/models/cargador-voltex.glb',
      highlights: [
        'Carga de vehículos eléctricos',
        'Conector y cable de carga',
        'Pantalla de interacción',
        'Instalación en patio',
      ],
      documentation: [],
      markers: {
        features: [
          { id: 'screen', label: 'Pantalla', type: 'Display interactivo', x: 50, y: 32, orbit: '0deg 78deg 110%', desc: 'Pantalla para selección de carga, estado del proceso y medios de pago.' },
          { id: 'connector', label: 'Conector', type: 'Pistola de carga', x: 38, y: 50, orbit: '330deg 75deg 112%', desc: 'Conector y cable de carga para conexión al vehículo eléctrico.' },
          { id: 'payment', label: 'Pago', type: 'Terminal / NFC', x: 50, y: 46, orbit: '0deg 76deg 108%', desc: 'Zona de pago contactless y con tarjeta para autorización de carga.' },
          { id: 'cabinet', label: 'Gabinete', type: 'Chasis', x: 50, y: 70, orbit: '0deg 80deg 115%', desc: 'Gabinete que aloja la electrónica de potencia y control del cargador.' },
        ],
      },
    },
  ],

  get categories() {
    return [...new Set(this.products.map((p) => p.category))];
  },

  get manufacturers() {
    return [...new Set(this.products.map((p) => p.manufacturer))];
  },
};
